### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by dawehner** [willwh/migrate_source_dir#9]
* Make recursive the only possible case. From my point of view you can simply not have a recursive directory with files, if you don't care about it. What do you think about that?
* Make it possible to specific multiple file extensions. Supporting both img and pngs seems to be a common usecase
* Unify the code in ```https://github.com/willwh/migrate_source_dir/blob/8.x-1.x/src/Plugin/migrate/source/Directory.php#L81``` to contain just one call to ```array_push```
* Let https://github.com/willwh/migrate_source_dir/blob/8.x-1.x/src/Plugin/migrate/source/Directory.php#L72 use a ```yield``` statement. This allows you to not store every file, but just yield as you go.

**Comment by willwh** [comment]
Thanks Daniel :) I actually did a slight rewrite of this, here: https://github.com/willwh/migrate_source_directory which is in sync with D.O.

I'm going to close this out and remove he repo :)

Thanks for the feedback!!

**Comment by dawehner** [comment]
Oh nice, suggestion: update the readme/project description
